In [8]:
import pandas as pd
import numpy as np

In [46]:
def color_negative_red(val):
    if val <= -30: color = 'red'
    elif -30 < val <= 30: color = 'white'
    else: color = 'orange'
    return 'color: %s' % color
df = pd.DataFrame(np.random.randint(-50, 50, size=(10, 10)), 
                  columns=['col1', 'col2', 'col3', 'col4', 'col5',
                           'col6', 'col7', 'col8', 'col9', 'col10']) 

df = df.style.applymap(color_negative_red)

In [47]:
df